export const ActionTypes = {
  SET_USER_DETAILS: "SET_USER_DETAILS",
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_PRODUCT_DETAILS: "SET_PRODUCT_DETAILS",
  REMOVE_PRODUCT_DETAILS: "REMOVE_PRODUCT_DETAILS",
  SET_PRODUCT_GROUP: "SET_PRODUCT_GROUP",
  REMOVE_PRODUCT_GROUP: "REMOVE_PRODUCT_GROUP",
  SET_CART: "SET_CART",
  UPDATE_CART_COUNT: "UPDATE_CART_COUNT",
  SET_WISHLIST: "SET_WISHLIST",
  UPDATE_WISHLIST_COUNT: "UPDATE_WISHLIST_COUNT",
};
